test: add smoke test for interactive TUI
Run the different user interfaces of Bob on a pty to trigger the
interactive console parts. No output is checked. It is assumed that
users will complain if the interactive output is garbage. We just want
to make sure that Bob does not crash on all output formats.

diff --git a/test/black-box/parallel/recipes/lib1.yaml b/test/black-box/parallel/recipes/lib1.yaml
--- a/test/black-box/parallel/recipes/lib1.yaml
+++ b/test/black-box/parallel/recipes/lib1.yaml
@@ -1,5 +1,6 @@
 packageVars: [FAIL_LIB1]
 packageScript: |
     if [ ${FAIL_LIB1:-} ] ; then
+        echo "Failing lib1" >&2
         exit 1
     fi
