test: verify that sandbox fingerprints are cached

diff --git a/test/sandbox-fingerprints/recipes/root.yaml b/test/sandbox-fingerprints/recipes/root.yaml
--- a/test/sandbox-fingerprints/recipes/root.yaml
+++ b/test/sandbox-fingerprints/recipes/root.yaml
@@ -7,6 +7,10 @@ depends:
 fingerprintIf: True
 fingerprintScript: |
     echo bob
+    if [[ ${FAIL_FINGERPRINT_IF_SET:+true} ]] ; then
+        echo "Fail as requested!" >&2
+        exit 1
+    fi
 
 checkoutDeterministic: True
 checkoutScript: |
